### PR TITLE
toxicity field bug

### LINKED ISSUE #7: Add more fields for plants
Let's add these fields to the plants model:

- Note (text area)
- Light requirements (select field - low, medium, high, direct sunlight)
- Water needs (select field - low, medium, high)
- Fertilization needs (text area)
- Toxicity (select field - non-toxic, to humans, to pets)
- Date acquired (datetime field)

All these fields are optional.

Add these fields to the new/edit plant form and display them on the plant show page.

### PR DESCRIPTION
**Pull request by Tomaszabc**
Do you have any idea why toxicity is cannot be defined in edit?

obraz

obraz

### CODE REVIEW

File: app/models/plant.rb [hunk 1]
```diff
@@ -6,6 +6,11 @@ class Plant < ApplicationRecord
   has_one :watering_reminder, dependent: :destroy
   has_one_attached :plant_image, dependent: :destroy
 
+  enum light_requirements: { low_light: 0, medium_light: 1, high_light: 2 }
+  enum water_needs: { low_water: 0, medium_water: 1, high_water: 2 }
+  enum toxicity: { non_toxic: 0, to_humans: 1, to_pets: 2 }
```
Comment (Ptrboro) [inline app/models/plant.rb]: Two suggestions:
1. I see you had to add `_light/_water` suffixes to avoid conflicting names. You can simplify this by passing `_suffix: true` option instead (this will generate methods like `low_light_requirements?`, `low_water_needs?` etc)
2. you don't need to use hashes in this case, you can just pass an array of possible values and rails will automatically assign numbers to them. 
```suggestion
  enum light_requirements: [:low, :medium, :high], _suffix: true
  enum water_needs: [:low, :medium, :high], _suffix: true
  enum toxicity: [:non_toxic, :to_humans, :to_pets]
```

File: app/views/plants/show.html.erb [hunk 2]
```diff
@@ -15,6 +15,12 @@
               <h1 class="text-3xl font-bold text-gray-800"><%= @plant.name %></h1>
               <p class="text-gray-600">Next watering: <%= @plant.next_watering&.strftime("%d-%m-%Y %H:%M") || 'No watering information' %></p>
               <p class="text-gray-600">Reminder: Every <%= @plant.watering_reminder&.quantity %> <%= @plant.watering_reminder&.unit %></p>
+              <p class="text-gray-600">Note: <%= @plant.note %></p>
+              <p class="text-gray-600">Light requirements: <%= @plant.light_requirements %></p>
+              <p class="text-gray-600">Water needs: <%= @plant.water_needs %></p>
+              <p class="text-gray-600">Fertilization needs: <%= @plant.fertilization_needs %></p>
+              <p class="text-gray-600">Toxicity: <%= @plant.toxicity %></p>
+              <p class="text-gray-600">Date acquired: <%= @plant.date_acquired %></p>
```
Comment (Ptrboro) [inline app/views/plants/show.html.erb]: something is wrong, adding these fields breaks the plant image (it should be square): 
Screenshot 2024-09-05 at 20 15 10

File: app/models/plant.rb (hunk 1 above)
Comment (Ptrboro) [reply app/models/plant.rb]: But using hashes has some advantages 👍  especially if you decide to remove one of the values later. 

e.g. for `enum toxicity: [:non_toxic, :to_humans, :to_pets]` non_toxic will be saved in the DB as 0, to_humans as 1 and to_pets as 2.

If you one of the values later and change it to:
`enum toxicity: [:non_toxic, :to_pets]`
then rails will start interpreting 0 as non_toxic and 1 as to_pets (which is incorrect) and will probably error out when the value is 2.

With has you don't have this problem because you explicitly tell rails how to translate each value:
```
enum toxicity: { non_toxic: 0, to_pets: 2 }
```

But tbh it is best not to use integers for enums at all and always use string type for columns. If you access the database directly then you will have a hard time understanding what 0, 1 and 2 mean. 
To use string you need to have these columns created as strings and use 
```
enum toxicity: {non_toxic: "non_toxic", to_humans: "to_humans", to_pets: "to_pets"}
```

No need to change anything, it is just worth to know :)

File: app/views/plants/show.html.erb (hunk 2 above)
Comment (Tomaszabc) [reply app/views/plants/show.html.erb]: I choose to use enums with strings as column type. I think it fits well. 
Some changes in image style were made but I will style it in different commit, after merging to main.

**Comment by Tomaszabc** [comment]
Branch with improvements added.

I think you should try to run app on your database, there can be mismatches due to enums change.
obraz

File: app/views/plants/show.html.erb (hunk 2 above)
Comment (Tomaszabc) [reply app/views/plants/show.html.erb]: obraz
